config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  root 'posts#index'
  get "sign_up" , to: "registrations#new"
  post "sign_up" , to: "registrations#create"
  delete "logout" , to: "sessions#destroy"
  get "sign_in" , to: "sessions#new"
  post "sign_in" , to: "sessions#create"
  get "password" , to: "passwords#edit" , as: :edit_password
  patch "password" , to: "passwords#update"
  get "password/reset" , to: "password_resets#new"
  post "password/reset" , to: "password_resets#create"

  get "password/reset/edit" , to: "password_resets#edit"
  patch "password/reset/edit" , to: "password_resets#update"

  get 'my_posts', to: 'posts#my_posts'

  # resources :posts
  resources :posts do
    post 'create_comment', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments

end

app/models/user.rb
 class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true , format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "must be a valid email address"}
  has_many :posts
  has_many :comments

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that!" if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index

    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end
  def create
    allert = "We have sent a link to reset your password"
    @user = User.find_by(email: params[:email])
    if params[:email] == ""
      allert = "Email cannot be blank"
    end
    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to root_path , notice: allert
  end

  def edit
    @user = User.find_signed!(params[:token] , purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token] , purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit
    end
  end
  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  def edit

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end
  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @comment = Comment.new
  end




  def my_posts
    @posts = Current.user.posts
    render 'my_posts'
  end


  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  # def create_comment
  #   @post = Post.find(params[:id])
  #   @comment = @post.comments.build(comment_params)
  #   @comment.user = Current.user
  #   if @comment.save
  #     redirect_to post_path(@post), notice: 'Comment created successfully.'
  #   else
  #     render :show
  #   end
  # end
  def create_comment
    @post = Post.find(params[:id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment created successfully.'
    else
      @comments = @post.comments
      render 'show'
    end
  end


  # @post = Post.find(params[:post_id])
  # @comment = @post.comments.build(comment_params.merge(user_id: Current.user.id))
  #
  # if @comment.save
  #   redirect_to post_path(@post), notice: 'Comment created successfully.'
  # else
  #   flash[:alert] = 'Failed to create comment.'
  #   redirect_to post_path(@post)
  # end







  def new
    @post = Post.new
  end

  def create
    @post = Current.user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post deleted successfully.'
  end


  private
  def post_params
    params.require(:post).permit(:title, :photo, :text)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end





end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # render plain: "Thanks for signing up!"
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up!"
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "You've logged in!"
        redirect_to root_path
    else
        flash[:alert] = "There was something wrong with your login details"
        render :new
    end
  end
  def destroy
     session[:user_id] = nil
     flash[:notice] = "You've logged out!"
     redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTweet</title>
    <link rel="shortcut icon" href="https://cdn.pixabay.com/photo/2013/07/12/17/46/twitter-152404_1280.png">
    <link rel="apple-touch-icon image_src" href="http://sstatic.net/stackoverflow/img/apple-touch-icon.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <style>
      @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap');
      body {
          font-family: 'Montserrat', sans-serif;
          background-color: #f5f5f5;
      }

      .container {
          max-width: 800px;
          margin-top: 50px;
      }

      .signn {
          max-width: 500px;
      }

      .card {
          border: none;
          border-radius: 20px;
          box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
      }

      .card-body {
          padding: 40px;
      }

      .card-title {
          font-size: 30px;
          font-weight: 700;
          text-align: center;
          margin-bottom: 30px;
      }

      .form-group label {
          font-size: 16px;
          font-weight: 700;
          margin-bottom: 10px;
      }

      .form-control {
          border: none;
          border-radius: 10px;
          padding: 15px;
          font-size: 16px;
          background-color: #f9f9f9;
          box-shadow: none;
      }

      .form-control:focus {
          box-shadow: none;
      }

      .btn-primary {
          border-radius: 10px;
          font-size: 18px;
          font-weight: 700;
          padding: 15px;
          width: 100%;
          background-color: #6c63ff;
          border: none;
      }

      .btn-primary:hover {
          background-color: #564ef8;
      }


      .alert {
          border-radius: 10px;
          font-size: 16px;
          font-weight: 700;
          padding: 15px;
          margin-top: 10px;
      }

      .alert-info {
          background-color: #bee5eb;
          color: #7790a9;
      }

      .alert-warning {
          background-color: #ffe8b4;
          color: #ff8000;
      }

      .navbar {
          background-color: #fff;
          box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
      }

      .navbar-brand {
          font-size: 24px;
          font-weight: 700;
          color: #6c63ff;
      }

      .navbar-toggler {
          border: none;
          background-color: transparent;
      }

      .navbar-toggler-icon {
          background-color: #6c63ff;
          width: 24px;
          height: 2px;
      }

      .navbar-nav .nav-link {
          font-size: 18px;
          font-weight: 700;
          color: #6c63ff;
          margin-left: 15px;
      }

      .navbar-nav .nav-link.active {
          color: lightslategray;
      }
      .custom-btn {
          width: 100px;
          height: 30px;
          display: flex;
          align-items: center;
          justify-content: center;
          text-align: center;
          transition: background-color 0.3s;
          margin-right: 15px;
          background-color:lightblue;
          color: #5f6967;
      }

      .disabled_btn{
          color: #5f6967;
      }

      .custom-btn.edit-btn:hover {
          background-color: #59a2bb;
          color: white;
      }

      .custom-btn.delete-btn:hover {
          background-color: lightcoral;
          color: white;
      }
  </style>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container pt-4">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex  align-items-center justify-content-center">
  <h1>Welcome to  Tweets</h1>
</div>

app/views/password_resets/edit.html.erb
<div class="container signn">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Reset your Password</h1>
      <%= form_with model: @user , url: password_reset_edit_path(token: params[:token]) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :password %>
          <%= form.password_field :password, class: "form-control", placeholder: "Enter your password" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
        </div>
        <div class="form-group">
          <%= form.submit "Reset Password", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="container signn">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Forgot your password?</h1>
      <%= form_with url: password_reset_path do |form| %>
        <div class="form-group mb-3">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
        <div class="form-group">
          <%= form.submit "Reset Password", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container signn">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Edit Post</h1>
      <%= form_with model: @post do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <ul class="mb-0">
              <% form.object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control", placeholder: "Enter the post title" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :photo %>
          <%= form.text_field :photo, class: "form-control", placeholder: "Enter the URL of the photo" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :text %>
          <%= form.text_area :text, class: "form-control", placeholder: "Enter the post text" %>
        </div>
        <div class="form-group">
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if Current.user %>
  <div class="d-flex align-items-center justify-content-center mb-5">
    <h1 class="display-3">Welcome to Tweets</h1>
  </div>

  <% @posts.each do |post| %>
    <div class="card mb-4">
      <img src="<%= post.photo %>"  class="card-img-top">

      <div class="card-body">
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text"><%= post.text %></p>
        <p class="card-text"><strong>Posted by:</strong> <%= post.user.email %></p>
        <div class="d-flex justify-content-end">
          <% if Current.user == post.user %>
            <%= link_to "Show Post", post_path(post), class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
            <%= link_to "Edit", edit_post_path(post), class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
            <%= button_to "Delete", post_path(post), method: :delete, class: "btn btn-sm custom-btn delete-btn rounded-pill" %>
          <% else %>
            <%= link_to "Show Post", post_path(post), class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
          <% end %>
        </div>
      </div>

      <div class="card-footer">
        <p class="fw-bold">Comments:</p>
        <% post.comments.last(3).each do |comment| %>
          <div class="d-flex align-items-start mb-2">
            <div>
              <span class="mb-0 fst-italic fw-semibold"><%= comment.user.email %> : </span><span class="light"><%= comment.comment %></span>
            </div>
          </div>
        <% end %>


        <form class="row g-3">
          <div class="col-10">
            <%= form_with url: create_comment_post_path(post) do |form| %>
              <%= form.hidden_field :name, value: Current.user.email %>
              <%= form.fields_for :comment, Comment.new do |comment_fields| %>
                <%= comment_fields.hidden_field :user_id, value: Current.user.id %>
                <%= comment_fields.hidden_field :post_id, value: post.id %>
                <%= comment_fields.text_field :comment,class: "form-control", placeholder: "Write a comment..." , style: "height: 20px"%>
          </div>
          <div class="col-2">
            <div class="form-group">
              <%= form.submit "Submit", class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
            </div>
          </div>
              <% end %>
            <% end %>
            </form>





      </div>
    </div>
  <% end %>

<% else %>
  <div class="d-flex align-items-center justify-content-center mb-5">
    <h1 class="display-3">Welcome to Tweets</h1>
  </div>
  <div class="d-flex align-items-center justify-content-center mb-5">
    <p class="lead">Please sign up or log in to see the posts.</p>
  </div>
<% end %>

app/views/posts/my_posts.html.erb
<div class="d-flex align-items-center justify-content-center mb-5">
  <h1 class="display-3">My Posts</h1>
</div>

<% @posts.each do |post| %>
  <div class="card mb-4">
    <div class="card-body">
      <h2 class="card-title"><%= post.title %></h2>
      <p class="card-text"><%= post.text %></p>
      <% if Current.user == post.user %>
        <div class="d-flex justify-content-end">
          <%= link_to "Show Post", post_path(post), class: "btn btn-sm  custom-btn edit-btn rounded-pill" %>
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
          <%= button_to "Delete", post_path(post), method: :delete, class: "btn btn-sm  custom-btn delete-btn rounded-pill" %>

        </div>
    <% end %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container signn">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Create Post</h1>
      <%= form_with model: @post do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <ul class="mb-0">
              <% form.object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control", placeholder: "Enter the post title" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :photo %>
          <%= form.text_field :photo, class: "form-control", placeholder: "Enter the URL of the photo" %>
        </div>
        <div class="form-group mb-3">
          <%= form.label :text %>
          <%= form.text_area :text, class: "form-control", placeholder: "Enter the post text" %>
        </div>
        <div class="form-group">
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- posts/show.html.erb -->
<div class="card">
  <div class="card-body">
    <img src="<%= @post.photo %>"  class="card-img-top">

    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-text"><%= @post.text %></p>
    <p class="card-text"><strong>Posted by:</strong> <%= @post.user.email %></p>
  </div>

  <form class="row g-3">
    <div class="col-10">
      <%= form_with url: create_comment_post_path(@post) do |form| %>
        <%= form.hidden_field :name, value: Current.user.email %>
        <%= form.fields_for :comment, Comment.new do |comment_fields| %>
          <%= comment_fields.hidden_field :post_id, value: @post.id %>
          <%= comment_fields.text_field :comment,class: "form-control", placeholder: "Write a comment..." , style: "height: 20px"%>

        <% end %>
        </div>
        <div class="col-2">
          <div class="form-group">
            <%= form.submit "Submit", class: "btn btn-sm custom-btn edit-btn rounded-pill" %>
          </div>
        </div>
      <% end %>
      </form>

</div>
<div class="mt-3">
  <h5><strong>Comments</strong></h5>
  <% @post.comments.each do |comment| %>
    <div class="card mb-2">
      <div class="card-body">
        <p class="card-text"><strong>Name:</strong> <%= comment.name %></p>
        <p class="card-text"><%= comment.comment %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice-alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert" id="alert-alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<script>
        document.addEventListener('DOMContentLoaded', function() {
                setTimeout(function() {
                        var noticeAlert = document.getElementById('notice-alert');
                        if (noticeAlert) {
                                noticeAlert.classList.add('fade-out');
                                noticeAlert.addEventListener('transitionend', function() {
                                        noticeAlert.style.display = 'none';
                                });
                        }

                        var alertAlert = document.getElementById('alert-alert');
                        if (alertAlert) {
                                alertAlert.classList.add('fade-out');
                                alertAlert.addEventListener('transitionend', function() {
                                        alertAlert.style.display = 'none';
                                });
                        }
                }, 1800);
        });
</script>

<style>
        .fade-out {
                opacity: 0;
                transition: opacity 0.5s;
        }
</style>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <%= link_to "MyTweet", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if Current.user %>
  <div class="navbar-nav">
        <%= link_to "My Posts", my_posts_path, class: "nav-link active" %>
        <%= link_to "Create Post", new_post_path, class: "nav-link active" %>
      </div>
    <% else %>
      <div class="navbar-nav">
        <%= link_to "My Posts", "", class: "nav-link active disabled_btn" %>
        <%= link_to "Create Post", "", class: "nav-link active disabled_btn" %>
      </div>
    <% end %>

  <div class="navbar-nav ms-auto">
        <% if Current.user %>
          <%= link_to Current.user.email, edit_password_path, class: "nav-link active" %>
          <%= button_to "Logout", logout_path, method: :delete, class: "nav-link active" %>
        <% else %>
          <%= link_to "Sign Up", sign_up_path, class: "nav-link active" %>
          <%= link_to "Log In", sign_in_path, class: "nav-link active" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>